# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=0.2.3
group=com.huziyang520.worldsettingsquit
java_version=25

# Common
minecraft_version=26.3
mod_name=World Settings Quick Exit
mod_author=Huziyang520
mod_id=worldsettingsquit
license=MIT
credits=KeenLib
description=Press ESC in the world options screen to apply changes and exit, just like the apply button. | \u5728\u4e16\u754c\u8bbe\u7f6e\u754c\u9762\u6309 ESC \u5373\u53ef\u4fdd\u5b58\u5e76\u9000\u51fa\uff0c\u7b49\u540c\u4e8e\u70b9\u51fb\u201c\u5e94\u7528\u66f4\u6539\u201d\u3002\u8f7b\u91cf\u5ba2\u6237\u7aef\u6a21\u7ec4\uff0c\u57fa\u4e8e KeenLib\u3002\u53cd\u9988: https://issue.mengcai.online/
minecraft_version_range=[26.3, 26.4)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.3-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.160.5+26.3
fabric_loader_version=0.19.5

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.3.0.1-beta

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
